### PR TITLE
Added Mark all as read button

### PR DESCRIPTION
**Pull request by LeoBeliik**
- Added a bookmark like button that only appears ~~in the front page and~~ when the player has unread entries.
- This moves the multiblock bookmark a little up in order to accommodate the new button.
- No new textures added.
- Added new entry in the english lang file **(plz check if it's correct)**

Default
FullBookmarked

### CODE REVIEW

**Comment by williewillus** [comment]
Looks like it marks everything in the book from my brief reading of the code.

Is it possible to only mark everything recursively down from where you're at? For example, if I'm in a specific category, the button only clears the entries in that category.

**Comment by LeoBeliik** [comment]
it marks as read all that's unlocked, I've though on making it category based but I think there's no point on that; I don't think people would to marks only some categories as read?

**Comment by LeoBeliik** [comment]
- Added the ability to mark only categories (and sub categories) as read
- Now the icon appears everywhere except on entries pages
- Added corresponding tooltip

**Comment by Hubry** [comment]
willie please merge this already or something

**Comment by williewillus** [comment]
Manually applied the patch

**Comment by LeoBeliik** [comment]
Oops, my bad. I should've asked before closing it.

**Pull request closed without merging**
